### PR TITLE
Inserted line breaks.

### PR DESCRIPTION
**Pull request by goyalyashpal**

### CODE REVIEW

**Comment by yashpalgoyal1304** [comment]
hi @Xaviju - it's just a quick Merge Request. Can u please accept? 😇

**Comment by Xaviju** [comment]
I'd be happy to update the Inkscape report URL but I do not understand why are you adding HTML line breaks or backslashes to the markdown

**Comment by goyalyashpal** [comment]
> why are you adding HTML line breaks or backslashes to the markdown

- [compare](https://github.com/PIWEEK/rethinkscape/pull/4/files?short_path=b335630#diff-b335630551682c19a781afebcf4d07bf978fb1f8ac04c6bf87428ed5106870f5) the rendered version of README on [c9e2a5707](../blob/c9e2a5707/README.md) with [master](../blob/master/README.md)
- Refer https://github.github.com/gfm/#hard-line-breaks for documentation

| MR | master |
| -- | -- |
![p-l][Screenshot_2021-06-07-23-46-16_1] | ![m-l][Screenshot_2021-06-07-23-46-53_1]
![p-p][Screenshot_2021-06-07-23-59-29_1] | ![m-p][Screenshot_2021-06-07-23-59-50_1]

[p-l]: [Screenshot_2021-06-07-23-46-16_1]
[m-l]: [Screenshot_2021-06-07-23-46-53_1]
[p-p]: [Screenshot_2021-06-07-23-59-29_1]
[m-p]: [Screenshot_2021-06-07-23-59-50_1]

[Screenshot_2021-06-07-23-46-16_1]: https://user-images.githubusercontent.com/19423063/121071346-70e27d00-c7ed-11eb-933a-64e48563daff.png
[Screenshot_2021-06-07-23-46-53_1]: https://user-images.githubusercontent.com/19423063/121071355-74760400-c7ed-11eb-939d-0530fce537f1.png
[Screenshot_2021-06-07-23-59-29_1]: https://user-images.githubusercontent.com/19423063/121071359-75a73100-c7ed-11eb-8051-d6c6a08f7dd4.png
[Screenshot_2021-06-07-23-59-50_1]: https://user-images.githubusercontent.com/19423063/121071365-76d85e00-c7ed-11eb-8790-1cfba24f252b.png

**Comment by yashpalgoyal1304** [comment]
pinging @Xaviju  :smile:

**Comment by goyalyashpal** [comment]
that's even better 👍 : https://github.com/PIWEEK/rethinkscape/commit/ef648f323ace635e0695da1b74ebc721874bc474

**Pull request merged**
